services:
  avisos-app:
    build: .
    image: avisos-app:latest
    container_name: avisos_core

    stdin_open: true
    tty: true

    environment:
      - TERM=xterm-256color

    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: avisos-broker
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  localstack:
    image: localstack/localstack:latest
    container_name: avisos-cloud
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  vision-api:
    image: codeproject/ai-server
    container_name: avisos-vision
    ports:
      - "32168:32168"
    environment:
      - VISION-DETECTION=True