/*
 * (C) Copyright 2026 Jawad Azeem
 * Apache 2.0 License
 */

package com.azeem.avisos.controller.web.event;

import com.azeem.avisos.controller.model.alarm.AlarmAnalysisRecord;
import org.springframework.context.ApplicationEvent;

/** Published when a new Alarm Analysis is generated by the AI Agent */
public class AlarmAnalysisCreatedEvent extends ApplicationEvent {
  private final AlarmAnalysisRecord analysisRecord;

  public AlarmAnalysisCreatedEvent(Object source, AlarmAnalysisRecord analysisRecord) {
    super(source);
    this.analysisRecord = analysisRecord;
  }

  public AlarmAnalysisRecord getAnalysisRecord() {
    return analysisRecord;
  }
}
