/*
 * (C) Copyright 2026 Jawad Azeem
 * Apache 2.0 License
 */

package com.azeem.avisos.node.common.telemetry;

import java.time.Instant;
import java.util.UUID;


/**
 * Immutable telemetry payload sent from a Node to the Controller service.
 *
 * <p>
 * This record represents a single telemetry event generated by a node device.
 * It contains both system metadata (device identity, battery state) and
 * sensor payload data intended for downstream processing (e.g., vision,
 * analytics, monitoring).
 * </p>
 *
 * <p>
 * The payload is typically serialized to JSON using Jackson and transmitted
 * over MQTT. Binary data (such as images) is Base64-encoded automatically
 * during JSON serialization.
 * </p>
 *
 * @param deviceId     unique identifier of the node that generated this telemetry
 * @param batteryLevel  current battery percentage of the node device
 * @param deviceName    human-readable name of the node
 * @param type         category of telemetry packet (e.g., HEARTBEAT, NETWORK_SCAN)
 * @param payload      raw sensor or image data produced by the node
 * @param timestamp    UTC timestamp indicating when the telemetry was generated
 */
public record TelemetryPacketDto(
        UUID deviceId,
        int batteryLevel,
        String deviceName,
        PacketTypeDto type,
        byte[] payload,
        Instant timestamp
) {}
